name: Dependency Review (upload)

on:
  workflow_run:
    workflows: ['Dependency Review (generate)']
    types: [completed]

permissions:
  actions: read
  contents: write

jobs:
  submit-dependency-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Download and submit dependency graph
        uses: gradle/actions/dependency-submission@v3
        with:
          dependency-graph: download-and-submit